import {useEffect,useState} from "react";
import {Menu as MenuIcon} from "lucide-react";import Menu from "./components/Menu";import Login from "./pages/Login";import Home from "./pages/Home";import Repositories from "./pages/Repositories";import Changes from "./pages/Changes";import Settings from "./pages/Settings";import Billing from "./pages/Billing";import Project from "./pages/Project";import SearchPage from "./pages/Search";import {github} from "./github";import {loadState,saveState} from "./storage";
export default function App(){const [user,setUser]=useState(null),[page,setPage]=useState("home"),[repos,setRepos]=useState([]),[repo,setRepo]=useState(null),[working,setWorking]=useState(null),[searchQuery,setSearchQuery]=useState(""),[openPath,setOpenPath]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{document.documentElement.style.setProperty("--ui-font",loadState("fontSize",16)+"px");github.session().then(x=>{if(x?.user){setUser(x.user);github.repos().then(setRepos).catch(()=>{})}}).catch(()=>{}).finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(repo){const saved=loadState(`project:${repo.id}`,null);if(saved)setWorking({repo,branch:saved.branch,files:saved.files||{},base:saved.base||{},changes:[]})}},[repo]);
 if(loading)return <div className="loading">Loading WyDev…</div>;if(!user)return <Login/>;
 const open=r=>{if(r){setRepo(r);setPage("project");saveState("recentProjects",[{id:r.id,full_name:r.full_name,repo:r,...loadState("recentProjects",[]).filter(x=>x.id!==r.id)}].slice(0,10))}else setPage("repos")};
 const workingChanges=working?.changes||[];
 const openFile=(path)=>{if(repo){setOpenPath(path);setPage("project");setWorking(w=>w?{...w,selected:path}:w)}};
 return <div className="app"><button className="mobileMenuButton" aria-label="Open menu" onClick={()=>document.body.classList.toggle("menu-open")}><MenuIcon size={20}/></button><Menu page={page} setPage={setPage} onSearch={q=>setSearchQuery(q)} onLogout={async()=>{await github.logout();location.reload()}}/><section className="content">
 {page==="home"&&<Home repos={repos} onOpen={open}/>} {page==="repos"&&<Repositories repos={repos} onOpen={open}/>} {page==="changes"&&<Changes changes={workingChanges} onSelect={openFile} onDiscard={working?.discard}/>} {page==="settings"&&<Settings/>} {page==="billing"&&<Billing/>} {page==="project"&&repo&&<Project repo={repo} openPath={openPath} onBack={()=>setPage("repos")} onWorkingState={setWorking}/>} {page==="search"&&<SearchPage repos={repos} onOpen={open} onNavigate={setPage} query={searchQuery} repoFiles={working?.files||{}} onOpenFile={openFile}/>} {page==="recent"&&<Recent onOpen={open}/>} {page==="help"&&<Help/>}
 </section></div>}
function Recent({onOpen}){const items=loadState("recentProjects",[]);return <div className="page"><header><div><span className="eyebrow">WORKSPACE</span><h1>Recent Projects</h1></div></header><section className="panel">{items.length?items.map(x=><button className="repoRow" key={x.id} onClick={()=>onOpen(x.repo||x)}><span><b>{x.full_name}</b><small>Recently opened</small></span><span>›</span></button>):<p className="muted">No recently opened repositories yet.</p>}</section></div>}
function Help(){return <div className="page"><header><div><span className="eyebrow">SUPPORT</span><h1>Help</h1></div></header><section className="panel"><h3>GETTING STARTED</h3><p>Sign in with GitHub, open a repository, edit files locally, review Changes, then Commit & Push.</p><p className="muted">GitHub remains the source of truth. WyDev never deploys or hosts your repository.</p><h3>WHEN A PUSH FAILS</h3><p>Pull the latest GitHub state and review the changes before retrying. WyDev refuses to overwrite a newer remote branch.</p><a href="https://github.com" target="_blank" rel="noreferrer">Open GitHub</a></section></div>}
