import Select from "../components/Select";
import {useEffect,useState} from "react";import {billing} from "../billing";
function b64(bytes){let s="";bytes.forEach(x=>s+=String.fromCharCode(x));return btoa(s)}
function nonce(){const a=crypto.getRandomValues(new Uint8Array(12));return Array.from(a).map(x=>String.fromCharCode(65+(x%26))).join("")}
async function keyBytes(key){if(!key)throw new Error("FLW_ENCRYPTION_KEY is not configured");const raw=Uint8Array.from(atob(key),c=>c.charCodeAt(0));if(raw.length!==32)throw new Error("Flutterwave encryption key must decode to 32 bytes");return raw}
async function encryptField(value,keyBytes,ns){const k=await crypto.subtle.importKey("raw",keyBytes,{name:"AES-GCM"},false,["encrypt"]);const out=await crypto.subtle.encrypt({name:"AES-GCM",iv:new TextEncoder().encode(ns)},k,new TextEncoder().encode(String(value)));return b64(new Uint8Array(out))}
async function encryptCard(card,key){const raw=await keyBytes(key),ns=nonce();return {nonce:ns,encrypted_card_number:await encryptField(card.number,raw,ns),encrypted_expiry_month:await encryptField(card.month,raw,ns),encrypted_expiry_year:await encryptField(card.year,raw,ns),encrypted_cvv:await encryptField(card.cvv,raw,ns)}}
export default function Billing(){const [status,setStatus]=useState({plan:"free"}),[cfg,setCfg]=useState({usd:9.99,ngn:0}),[currency,setCurrency]=useState("NGN"),[busy,setBusy]=useState(false),[err,setErr]=useState(""),[card,setCard]=useState({number:"",expiry:"",cvv:""}),[auth,setAuth]=useState(null),[authValue,setAuthValue]=useState("");
 useEffect(()=>{billing.status().then(setStatus).catch(e=>setErr(e.message));billing.config().then(setCfg).catch(()=>{})},[]);
 const verify=async(id,reference)=>{const v=await billing.verify({id,reference});if(v.active){location.reload();return true}setErr("Payment is still pending. Complete the required authorization and try again.");return false};
 const pay=async()=>{setBusy(true);setErr("");try{const [month,year]=card.expiry.split("/");if(!month||!year||card.number.length<12||card.cvv.length<3)throw new Error("Enter a valid card number, MM/YY and CVV.");const enc=await encryptCard({number:card.number,month,year,cvv:card.cvv},import.meta.env.FLW_ENCRYPTION_KEY);const d=await billing.checkout({currency,email:status.email||undefined,payment_method:{type:"card",card:enc}});const data=d?.data||{};const next=data.next_action;const url=next?.redirect_url?.url||next?.redirect_url;if(url){location.href=url;return}if(data.id&&next?.type){setAuth({id:data.id,reference:data.reference,type:next.type,nonce:next?.requires_pin?.nonce||next?.authorization?.pin?.nonce||null});return}if(data.id)await verify(data.id,data.reference);else throw new Error("Flutterwave did not return a payment action")}catch(e){setErr(e.message)}finally{setBusy(false)}};
 const authorize=async()=>{setBusy(true);setErr("");try{if(!authValue)throw new Error("Enter the required authorization value.");let authorization;if(auth.type==="requires_pin"||auth.type==="authorize"){const raw=await keyBytes(import.meta.env.FLW_ENCRYPTION_KEY),ns=auth.nonce||nonce();authorization={type:"pin",pin:{nonce:ns,encrypted_pin:await encryptField(authValue,raw,ns)}}}else if(auth.type==="requires_otp"){authorization={type:"otp",otp:{code:authValue}}}else throw new Error(`Flutterwave requested ${auth.type}; complete the bank authorization step if a redirect is provided.`);const d=await billing.authorize({id:auth.id,authorization});const next=d?.data?.next_action;const url=next?.redirect_url?.url||next?.redirect_url;if(url){location.href=url;return}if(d?.data?.status==="succeeded")await verify(auth.id,auth.reference);else {setAuthValue("");setErr("Authorization submitted. Check the payment status and continue if another step is requested.")}}catch(e){setErr(e.message)}finally{setBusy(false)}};
 if(status.plan==="pro")return <div className="page"><header><div><span className="eyebrow">BILLING</span><h1>WyDev Pro</h1></div></header><section className="panel"><h3>PLAN</h3><p><b>Pro active</b>{status.expiresAt&&` · active until ${new Date(status.expiresAt).toLocaleDateString()}`}</p><p className="muted">Monthly renewal is handled automatically when a reusable payment method is available.</p></section></div>;
 return <div className="page"><header><div><span className="eyebrow">BILLING</span><h1>WyDev Pro</h1></div></header><section className="panel proOffer"><h3>PRO INCLUDES</h3><ul className="featureList"><li><b>Higher repository limits</b><span>Work with more GitHub repositories from one WyDev workspace.</span></li><li><b>Advanced developer workspace</b><span>Get the full WyDev editing, file management and project workflow.</span></li><li><b>Priority AI assistance</b><span>Use AI-powered developer help with higher access than the free plan.</span></li><li><b>Faster workflow</b><span>Designed for developers who need fewer limits while building and maintaining projects.</span></li><li><b>Pro-only capabilities</b><span>Unlock features marked Pro throughout WyDev as they become available.</span></li></ul><p className="muted">Your Pro benefits are tied to your WyDev account and remain available while your subscription is active.</p></section><section className="panel"><h3>PLAN</h3><div className="price">{currency==="NGN"?(cfg.ngn?`₦${cfg.ngn.toLocaleString()}`:"NGN price not configured"):`$${(cfg.usd??9.99).toFixed(2)}`}/month</div><Select value={currency} onChange={setCurrency} options={[{value:"NGN",label:"NGN — ₦"},{value:"USD",label:"USD — $"}]} />{!auth?<><input className="searchInput" inputMode="numeric" autoComplete="cc-number" placeholder="Card number" value={card.number} onChange={e=>setCard({...card,number:e.target.value.replace(/\D/g,"")})}/><input className="searchInput" inputMode="numeric" autoComplete="cc-exp" placeholder="MM/YY" value={card.expiry} onChange={e=>setCard({...card,expiry:e.target.value.replace(/[^0-9/]/g,"")})}/><input className="searchInput" inputMode="numeric" autoComplete="cc-csc" placeholder="CVV" value={card.cvv} onChange={e=>setCard({...card,cvv:e.target.value.replace(/\D/g,"")})}/><button className="primary" disabled={busy} onClick={pay}>{busy?"Processing…":"Pay securely with Flutterwave"}</button></>:<><p>Flutterwave requires <b>{auth.type.replace("requires_","")}</b> authorization.</p><input className="searchInput" inputMode="numeric" autoComplete="one-time-code" placeholder={auth.type==="requires_pin"?"Card PIN":"OTP"} value={authValue} onChange={e=>setAuthValue(e.target.value)}/><button className="primary" disabled={busy} onClick={authorize}>{busy?"Authorizing…":"Continue payment"}</button></>}<p className="muted">Card fields are encrypted in your browser with AES-256 before WyDev sends payment data to Flutterwave.</p>{err&&<p className="error">{err}</p>}</section></div>}
