import {useEffect,useMemo,useState} from "react";
import {GitPullRequest,GitCompare,Issue,Package,Star,GitFork,RefreshCw,Plus,Merge,ExternalLink} from "lucide-react";
import {github} from "../github";
import {billing} from "../billing";
import {loadState,saveState} from "../storage";
import {promptDialog,confirmDialog} from "../dialog";
import {toastError,toastSuccess} from "../toast";
import Select from "../components/Select";
import {openExternal} from "../utils";

export default function GitHubHub({repos}){
 const [repoId,setRepoId]=useState(()=>loadState("githubHubRepo","")||"");
 const repo=useMemo(()=>repos.find(r=>String(r.id)===String(repoId))||repos[0]||null,[repos,repoId]);
 const [drive,setDrive]=useState(false),[tab,setTab]=useState("overview"),[issues,setIssues]=useState([]),[pulls,setPulls]=useState([]),[releases,setReleases]=useState([]),[compare,setCompare]=useState(null),[starred,setStarred]=useState(false),[branches,setBranches]=useState([]),[busy,setBusy]=useState(false),[pro,setPro]=useState(false);
 const owner=repo?.owner?.login||repo?.full_name?.split("/")[0];
 const load=async()=>{if(!repo)return;setBusy(true);try{const [i,p,r,b,st,s]=await Promise.all([github.issues(owner,repo.name),github.pullList(owner,repo.name),github.releases(owner,repo.name),github.branches(owner,repo.name),github.starStatus(owner,repo.name),billing.status()]);setIssues(i.issues||[]);setPulls(p.pulls||[]);setReleases(r.releases||[]);setBranches(Array.isArray(b)?b:[]);setStarred(!!st.starred);setPro(s.plan==="pro");}catch(e){toastError(e.message||"Could not load GitHub workspace.")}finally{setBusy(false)}};
 useEffect(()=>{if(repo&&!repoId){setRepoId(String(repo.id));saveState("githubHubRepo",String(repo.id));}},[repo,repoId]);
 useEffect(()=>{load()},[repo?.id]);
 const createIssue=async()=>{const x=await promptDialog({title:"Quick issue",confirmLabel:"Create issue",fields:[{key:"title",label:"Title",placeholder:"Describe the task"},{key:"body",label:"Details",placeholder:"Optional details",required:false}]});if(!x)return;try{await github.createIssue(owner,repo.name,x);toastSuccess("Issue created");load()}catch(e){toastError(e.message)}};
 const createRelease=async()=>{const x=await promptDialog({title:"Create release",confirmLabel:"Publish release",fields:[{key:"tag_name",label:"Tag",placeholder:"v1.0.0"},{key:"name",label:"Release name",placeholder:"Version 1.0.0",required:false},{key:"body",label:"Notes",placeholder:"Release notes",required:false}]});if(!x)return;try{await github.createRelease(owner,repo.name,x);toastSuccess("Release published");load()}catch(e){toastError(e.message)}};
 const compareRefs=async()=>{const x=await promptDialog({title:"Compare branches",confirmLabel:"Compare",fields:[{key:"base",label:"Base",placeholder:repo.default_branch||"main"},{key:"head",label:"Head",placeholder:"feature/my-change"}]});if(!x)return;try{const d=await github.compare(owner,repo.name,x.base,x.head);setCompare(d);setTab("compare")}catch(e){toastError(e.message)}};
 const merge=async(n)=>{const ok=await confirmDialog({title:`Merge pull request #${n}?`,message:"WyteLab will ask GitHub to squash-merge this pull request. This cannot be undone from WyteLab.",confirmLabel:"Merge pull request"});if(!ok)return;try{const d=await github.mergePull(owner,repo.name,n,{method:"squash"});toastSuccess(d.merged?"Pull request merged":"GitHub did not merge this pull request");load()}catch(e){toastError(e.message)}};
 const toggleStar=async()=>{try{setStarred(!starred);await (starred?github.unstar(owner,repo.name):github.star(owner,repo.name));toastSuccess(starred?"Removed star":"Repository starred")}catch(e){setStarred(starred);toastError(e.message)}};
 const fork=async()=>{try{await github.fork(owner,repo.name);toastSuccess("Fork requested. GitHub is creating it now.")}catch(e){toastError(e.message)}};
 const driveExport=async()=>{setDrive(true);try{const d=await github.driveExport(owner,repo.name,repo.default_branch||"main");toastSuccess(`Saved ${d.file?.name||"repository ZIP"} to Google Drive`);if(d.file?.webViewLink)openExternal(d.file.webViewLink)}catch(e){if(e.code==="GOOGLE_DRIVE_NOT_CONNECTED"||e.status===401){location.href="/api/auth/google";return}toastError(e.message||"Google Drive export failed")}finally{setDrive(false)}};
 if(!repo)return <div className="page"><header><div><span className="eyebrow">GITHUB TOOLS</span><h1>Developer Hub</h1></div></header><section className="panel"><p className="muted">Open a repository first.</p></section></div>;
 return <div className="page"><header><div><span className="eyebrow">GITHUB TOOLS</span><h1>Developer Hub</h1><p className="muted">Common GitHub work, condensed into one mobile-friendly workspace.</p></div><button className="ghost" onClick={load} disabled={busy}><RefreshCw size={16}/>Refresh</button></header>
 <section className="panel"><Select value={repoId} onChange={e=>{setRepoId(e.target.value);saveState("githubHubRepo",e.target.value)}} options={repos.map(r=>({value:String(r.id),label:r.full_name}))} label="Repository"/><div className="hubQuick"><button onClick={createIssue}><Plus size={15}/>Issue</button><button onClick={compareRefs}><GitCompare size={15}/>Compare</button><button onClick={createRelease}><Package size={15}/>Release</button><button onClick={toggleStar}><Star size={15} fill={starred?"currentColor":"none"}/>{starred?"Starred":"Star"}</button><button onClick={fork}><GitFork size={15}/>Fork</button><button onClick={driveExport} disabled={drive}><ExternalLink size={15}/>{drive?"Saving…":"Save ZIP to Drive"}</button></div></section>
 <nav className="hubTabs">{[["overview","Overview"],["issues",`Issues (${issues.length})`],["pulls",`PRs (${pulls.length})`],["releases",`Releases (${releases.length})`],["compare","Compare"]].map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
 {tab==="overview"&&<section className="panel"><h3>QUICK WORK</h3><div className="hubGrid"><button onClick={()=>setTab("issues")}><Issue size={18}/><b>Issues</b><span>Track bugs and tasks without hunting through GitHub.</span></button><button onClick={()=>setTab("pulls")}><GitPullRequest size={18}/><b>Pull requests</b><span>Review open PRs and merge when ready.</span></button><button onClick={()=>setTab("releases")}><Package size={18}/><b>Releases</b><span>Publish releases and keep notes in one place.</span></button><button onClick={compareRefs}><GitCompare size={18}/><b>Branch compare</b><span>See ahead/behind counts and changed files quickly.</span></button></div><p className="muted">Branches available: {branches.length}. {pro?"Pro is active — advanced developer controls are unlocked.":"Free includes the core tools; Pro adds advanced automation and repository controls."}</p></section>}
 {tab==="issues"&&<section className="panel"><div className="panelTitleRow"><h3>OPEN ISSUES</h3><button className="primary" onClick={createIssue}><Plus size={15}/>New issue</button></div>{issues.length?issues.map(x=><article className="hubRow" key={x.id}><div><b>#{x.number} {x.title}</b><small>{x.user?.login||"Unknown"} · {new Date(x.updated_at).toLocaleDateString()}</small></div><button onClick={()=>openExternal(x.html_url)}><ExternalLink size={15}/></button></article>):<p className="muted">No open issues.</p>}</section>}
 {tab==="pulls"&&<section className="panel"><h3>OPEN PULL REQUESTS</h3>{pulls.length?pulls.map(x=><article className="hubRow" key={x.id}><div><b>#{x.number} {x.title}</b><small>{x.user?.login||"Unknown"} · {x.head?.ref||""} → {x.base?.ref||""}</small></div><div className="hubRowActions"><button onClick={()=>openExternal(x.html_url)}><ExternalLink size={15}/></button><button onClick={()=>merge(x.number)} title="Squash merge"><Merge size={15}/></button></div></article>):<p className="muted">No open pull requests.</p>}</section>}
 {tab==="releases"&&<section className="panel"><div className="panelTitleRow"><h3>RELEASES</h3><button className="primary" onClick={createRelease}><Plus size={15}/>New release</button></div>{releases.length?releases.map(x=><article className="hubRow" key={x.id}><div><b>{x.name||x.tag_name}</b><small>{x.tag_name} · {new Date(x.published_at||x.created_at).toLocaleDateString()}</small></div><button onClick={()=>openExternal(x.html_url)}><ExternalLink size={15}/></button></article>):<p className="muted">No releases yet.</p>}</section>}
 {tab==="compare"&&<section className="panel"><h3>COMPARE RESULT</h3>{compare?<><p><b>{compare.status}</b> · {compare.ahead_by} ahead · {compare.behind_by} behind · {compare.total_commits} commits</p><div className="hubList">{(compare.files||[]).map(f=><div key={f.filename}><code>{f.filename}</code><small>{f.status} · +{f.additions} −{f.deletions}</small></div>)}</div>{compare.html_url&&<button className="ghost" onClick={()=>openExternal(compare.html_url)}>Open comparison <ExternalLink size={15}/></button>}</>:<p className="muted">Choose two branches or refs with Compare to see the result here.</p>}</section>}
 </div>;
}
