plugins { id 'com.android.application' }
android { namespace 'com.wydev.wrapper'; compileSdk 35; defaultConfig { applicationId 'com.wydev.wrapper'; minSdk 23; targetSdk 35; versionCode 1; versionName '1.0' } }
dependencies { implementation "androidx.fragment:fragment:1.8.5"; implementation "androidx.core:core:1.13.1"; implementation "androidx.activity:activity:1.9.3"; implementation "androidx.appcompat:appcompat:1.7.0" }
